name: Ubuntu RDP with Ngrok and SSH

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    env:
      RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
      - name: Download Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update
          sudo apt install -y ngrok

      - name: Connect your Ngrok account
        run: ngrok config add-authtoken $NGROK_AUTH_TOKEN

      - name: Enable RDP and Install xrdp and xfce4
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4 xfce4-goodies
          sudo ufw allow 3389/tcp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          echo "xfce4-session" > ~/.xsession

      - name: Add User 'rajnikant'
        run: |
          sudo adduser --gecos "" --disabled-password rajnikant
          echo "rajnikant:rajni9771" | sudo chpasswd
          sudo usermod -aG sudo rajnikant
          sudo mkdir -p /home/rajnikant/.config
          sudo chown -R rajnikant:rajnikant /home/rajnikant/.config

      - name: Configure xfce4 session for xrdp
        run: |
          sudo -u rajnikant bash -c 'echo "xfce4-session" > /home/rajnikant/.xsession'
          sudo -u rajnikant bash -c 'mkdir -p /home/rajnikant/.config/xfce4/xfconf/xfce-perchannel-xml'
          sudo -u rajnikant bash -c 'echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><channel name=\"xfce4-session\" version=\"1.0\"><property name=\"general\" type=\"empty\"><property name=\"SaveOnExit\" type=\"bool\" value=\"false\"/></property></channel>" > /home/rajnikant/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-session.xml'

      - name: Install and Configure SSH
        run: |
          sudo apt-get install -y openssh-server
          sudo ufw allow 22/tcp
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Create Ngrok Tunnel for RDP
        run: |
          #ngrok tcp 3389 --log=stdout > ngrok_rdp_output.txt &

      - name: Create Ngrok Tunnel for SSH
        run: |
          ngrok tcp 22 --log=stdout > ngrok_ssh_output.txt &

      - name: Show Ngrok Tunnel URLs
        run: |
          sleep 12 # Wait for Ngrok to start the tunnels (adjust time as needed)
          echo "RDP Tunnel URL:"
          #cat ngrok_rdp_output.txt | grep "url="
          echo "SSH Tunnel URL:"
          cat ngrok_ssh_output.txt | grep "url="

      - name: Run Loop
        run: |
          while true; do
            sleep 600 # Sleep for 10 minutes
            echo "RDP Tunnel URL:"
            #cat ngrok_rdp_output.txt | grep "url="
            echo "SSH Tunnel URL:"
            cat ngrok_ssh_output.txt | grep "url="
          done
