name: Ubuntu RDP with Ngrok

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    env:
      RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
      - name: Download Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null \
          && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list \
          && sudo apt update \
          && sudo apt install -y ngrok

      - name: Connect your Ngrok account
        run: ngrok config add-authtoken $NGROK_AUTH_TOKEN

      - name: Enable RDP and Install xrdp
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp xfce4 xfce4-goodies
          sudo ufw allow 3389/tcp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Configure xfce4 session for xrdp
        run: |
          echo "xfce4-session" > ~/.xsession

      - name: Add User 'rajnikant'
        run: |
          sudo adduser --gecos "" --disabled-password rajnikant
          echo "rajnikant:rajni9771" | sudo chpasswd
          sudo usermod -aG sudo rajnikant

      - name: Create Ngrok Tunnel
        run: |
          ngrok tcp 3389 --log=stdout > ngrok_output.txt &

      - name: Show Ngrok Tunnel URL
        run: |
          sleep 12 # Wait for Ngrok to start the tunnel (adjust time as needed)
          cat ngrok_output.txt | grep "url="

      - name: Run Loop
        run: |
          while true; do
            sleep 60 # Sleep for 10 minutes
            cat ngrok_output.txt | grep "url="
          done
