name: Ubuntu RDP with Ngrok

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 9999

    env:
      RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}

    steps:
      - name: Download Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc 
          sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null  
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" || sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update 
          sudo apt install ngrok

      - name: Connect your Ngrok account
        run: ngrok config add-authtoken $NGROK_AUTH_TOKEN
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Enable RDP and Install xrdp
        run: |
          sudo apt-get update
          sudo apt-get install -y xrdp
          sudo ufw allow 3389/tcp
          sudo systemctl enable xrdp
          sudo systemctl start xrdp

      - name: Create Tunnel
        run: |
          ngrok tcp 3389 > ngrok_output.txt &

      - name: Show Ngrok Tunnel URL
        run: |
          sleep 12 # Wait for Ngrok to start the tunnel (adjust time as needed)
          cat ngrok_output.txt

      - name: Run Loop
        run: |
          while true; do
            sleep 10 # Sleep for 6 hours
             cat ngrok_output.txt 
          done
